from templatekit.builder import cookiecutter_project_builder

# Run cookiecutter to generate the 'TESTTR-0' report
env = Environment(BUILDERS={'Cookiecutter': cookiecutter_project_builder})
env.Cookiecutter(AlwaysBuild(Dir('TESTTR-0')),
                 'cookiecutter.json',
                 cookiecutter_context={'series': 'TESTTR',
                                       'github_org': 'lsst-dm',
                                       'serial_number': '0',
                                       'date': '2020-01-01'})
