sudo: false
language: python
matrix:
  include:
    - python: '3.6'
      install:
        - 'pip install -r <(curl https://raw.githubusercontent.com/lsst/linting/master/requirements.txt)'
      script:
        - flake8
