# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['exampleOne',
                                  'exampleTwo/exampleTwo',
                                  'exampleThree/exampleThree'], addUnderscore=False)
