from templatekit.builder import cookiecutter_project_builder

# Run cookiecutter to generate the 'EXAMPLE-0' document.
env = Environment(BUILDERS={"Cookiecutter": cookiecutter_project_builder})
env.Cookiecutter(
    AlwaysBuild(Dir("EXAMPLE-0")),
    "cookiecutter.json",
    cookiecutter_context={
        "github_org": "lsst",
        "series": "EXAMPLE",
        "serial_number": "0",
        "first_author_given": "First2",
        "first_author_family": "Author2",
        "first_author_author_id": "test2",
        "date": "2020-01-01",
    },
)
