sudo: false
language: python
matrix:
  include:
    - python: '3.6'
      install:
        - 'pip install -r <(curl project_templates/stack_package/{{cookiecutter.package_name}}/.travis.yml)'
      script:
        - flake8
