name: CI

"on": [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install "lander<2.0.0"
          python -m pip install pyyaml

      - name: Compile author list
        run: |
          make authors.tex

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sqrereadonly
          password: ${{ secrets.DOCKERHUB_SQREREADONLY_TOKEN }}

      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'

      - name: Landing page upload
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --upload --pdf TESTN-000.pdf --ltd-product testn-000 --title "Document Title" --handle "TESTN-000" --lsstdoc "TESTN-000.tex"
