name: Docker

"on":
  push:
    branches:
      - "tickets/**"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Define the Docker tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF} | sed -E 's,refs/(heads|tags)/,,' | sed -E 's,/,-,g')

      - name: Print the tag
        id: print
        run: echo ${{steps.vars.outputs.tag}}

      - name: Log into Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull previous images
        run: |
          docker pull lsstsqre/example:deps-${{steps.vars.outputs.tag}} || true
          docker pull lsstsqre/example:${{steps.vars.outputs.tag}} || true

      - name: Build the dependencies Docker image
        run: |
          docker build --target dependencies-image \
            --cache-from=lsstsqre/example:deps-${{steps.vars.outputs.tag}} \
            --tag lsstsqre/example:deps-${{steps.vars.outputs.tag}} .

      - name: Build the runtime Docker image
        run: |
          docker build --target runtime-image \
            --cache-from=lsstsqre/example:${{steps.vars.outputs.tag}} \
            --tag lsstsqre/example:${{steps.vars.outputs.tag}} .

      - name: Push Docker images
        run: |
          docker push lsstsqre/example:deps-${{steps.vars.outputs.tag}}
          docker push lsstsqre/example:${{steps.vars.outputs.tag}}
