from templatekit.builder import file_template_builder, line_format_builder


env = Environment(BUILDERS={'FileTemplate': file_template_builder,
                            'LineFormat': line_format_builder},
                  line_format='# {}')
env.LineFormat('template.py.jinja', '../stack_license_preamble_txt/template.txt.jinja')
env.FileTemplate('example.py', 'template.py.jinja')
