name: docgen from Jira
on: workflow_dispatch

jobs:
   generate:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for metadata
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Set up pandoc
        uses: pandoc/actions/setup@v1

      - name: docugen
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          ZEPHYR_TOKEN: ${{ secrets.ZEPHYR_TOKEN }}
        run: |
          docsteady  --namespace DM generate-tpr --includeall True LVV-P73  TESTTR-0.tex
        shell: bash

      - name: Create commit
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git add attachments jira_imgs
          git commit -am "Update from JIRA."
          git push

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sqrereadonly
          password: ${{ secrets.DOCKERHUB_SQREREADONLY_TOKEN }}

      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'

      - name: Landing page upload
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --upload --pdf TESTTR-0.pdf --lsstdoc TESTTR-0.tex --ltd-product testtr-0 --extra-download TESTTR-0-plan.pdf
