apiVersion: apps/v1
kind: Deployment
metadata:
  name: "example"
  labels:
    app.kubernetes.io/name: "example"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "example"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "example"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app
          imagePullPolicy: "IfNotPresent"
          # Use images field in a Kustomization to set/update image tag
          image: "lsstsqre/example"
          ports:
            - containerPort: 8080
              name: "app"
          envFrom:
            - configMapRef:
                name: "example"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
