apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ cookiecutter.module_name }}"
  labels:
    app.kubernetes.io/name: "{{ cookiecutter.name }}"
data:
  # These configurations are injected as environment variables into the
  # app container.
  SAFIR_NAME: "{{ cookiecutter.module_name }}"
  SAFIR_PROFILE: "production"
  SAFIR_LOGGER: "{{ cookiecutter.module_name }}"
  SAFIR_LOG_LEVEL: "INFO"
