apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: "ghcr.io/{{ cookiecutter.github_org }}/{{ cookiecutter.name | lower }}"
    newTag: 0.0.0

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
