apiVersion: v1
kind: Service
metadata:
  name: "{{ cookiecutter.module_name }}"
  labels:
    app.kubernetes.io/name: "{{ cookiecutter.name }}"
spec:
  ports:
    - name: "{{ cookiecutter.module_name }}-http"
      protocol: "TCP"
      port: 8080
      targetPort: "app"
  selector:
    app.kubernetes.io/name: "{{ cookiecutter.module_name }}"
