name: Python CI

"on":
  merge_group: {}
  pull_request: {}
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice. This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - "dependabot/**"
      - "gh-readonly-queue/**"
      - "renovate/**"
      - "t/**"
      - "tickets/**"
      - "u/**"
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python:
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # full history for setuptools-scm

      # Use floating latest uv version, since we've had great luck with
      # backward compatibility. If we run into the problems in the future, we
      # can do something more complicated with a pinned version updated with a
      # script run by `make update-deps` similar to service packages.
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python }}

      - name: Run nox
        run: uv run --only-group=nox nox -P $UV_PYTHON -s lint typing test

  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      docs-specific: ${{ steps.filter.outputs.docs-specific }}

    steps:
      - uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            docs:
              - "CHANGELOG.md"
              - "docs/**"
              - "src/**"
            docs-specific:
              - "CHANGELOG.md"
              - "docs/**"

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: changes
    if: >
      (needs.changes.outputs.docs == 'true')
      || (github.event_name == 'workflow_dispatch')
      || (github.event_name == 'release' && github.event.action == 'published')

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # full history for setuptools-scm

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install extra packages
        run: |
          sudo apt-get update
          sudo apt-get install -u graphviz

      - name: Run nox
        run: uv run --only-group=nox nox -s docs

      # Only attempt documentation uploads for tagged releases and pull
      # requests from ticket branches in the same repository. This avoids
      # version clutter in the docs and failures when a PR doesn't have access
      # to secrets.
      - name: Upload to LSST the Docs
        uses: lsst-sqre/ltd-upload@v1
        with:
          project: "example"
          dir: "docs/_build/html"
          username: ${{ secrets.LTD_USERNAME }}
          password: ${{ secrets.LTD_PASSWORD }}
        if: >
          (github.event_name == 'push' && github.ref_name == 'main')
          || (github.event_name == 'release'
              && github.event.action == 'published')
          || (github.event_name == 'workflow_dispatch')
          || (github.event_name == 'pull_request'
              && (startsWith(github.head_ref, 'tickets/')
                  || startsWith(github.head_ref, 't/'))
              && needs.changes.outputs.docs-specific == 'true')

  linkcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    needs: changes
    if: >
      (needs.changes.outputs.docs == 'true')
      || (github.event_name == 'workflow_dispatch')

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # full history for setuptools-scm

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Install extra packages
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Run nox
        run: uv run --only-group=nox nox -s docs-linkcheck

  test-packaging:
    name: Test packaging
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [test, docs]

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # full history for setuptools-scm

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Build the packages
        run: uv build --no-sources --all-packages

  pypi:
    # This job requires set up:
    # 1. Set up a trusted publisher for PyPI
    # 2. Set up a "pypi" environment in the repository
    # See https://github.com/lsst-sqre/build-and-publish-to-pypi
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [test, docs, test-packaging]
    environment:
      name: pypi
      url: https://pypi.org/p/example
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # full history for setuptools-scm

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build the packages
        run: uv build --no-sources --all-packages

      - name: Publish the packages
        run: uv publish
